---
version: '3'
includes:
  terraform:
    taskfile: ../../tasks/terraform.yml
vars:
  WORKSPACE_NAME: dex-aad
tasks:
  destroy:
    cmds:
      - task: terraform:destroy
  default:
    cmds:
      - task: terraform:workspace-new
      - task: terraform:workspace-select
      - task: terraform:init
      - task: terraform:validate
      - task: terraform:plan
      - task: terraform:apply
