---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-all-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: doppler-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /
        name:
          regexp: ".*"