---
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart-grafana-agent.labels" . | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  image: grafana/agent:v0.32.1
  logLevel: info
  serviceAccountName: '{{ include "chart-grafana-agent.serviceAccountName" . }}'
  metrics:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-metrics
    externalLabels:
      cluster: kind
  logs:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-logs
