---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart-grafana-agent.serviceAccountName" . }}
  labels:
    {{- include "chart-grafana-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
