---
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
webserver:
  defaultUser:
    username: admin
    role: Admin
    email: andrew.rothstein@gmail.com
    firstName: Drew
    lastName: Rothstein
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/andrewrothstein/airflow-dags.git
    branch: main
    subPath: ""
workers:
  keda:
    enabled: true
