---
redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

global:
  domain: argocd.elephant-frog.ts.net

certificate:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: tailscale
    tls: true
