---
redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.elephant-frog.ts.net

certificate:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: tailscale
    tls: true
