---
databaseUpgradeReady: true
unifiedUpgradeAllowed: true
artifactory:
  postgresql:
    enabled: true
  nginx:
    enabled: false
  ingress:
    enabled: true
    className: tailscale
    defaultBackend:
      enabled: true
    hosts:
      - artifactory
    routerPath: /
    artifactoryPath: /artifactory/
    tls:
      - hosts:
          - artifactory
