---
conf:
  cache: "2Gi"
  max-sql-memory: "2Gi"
tls:
  certs:
    selfSigner:
      enabled: false
    certManager: true
    certManagerIssuer:
      kind: ClusterIssuer
      name: selfsigned-cluster-issuer
