---
coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-pg-chart-cnpg-instance-app
          key: uri
    - name: CODER_AUTO_IMPORT_TEMPLATES
      value: kubernetes
