---
version: '3'
tasks:
  _apply:
    internal: true
    vars:
      p: '{{ .p }}'
      f: '{{ .f }}'
      cmd: '{{ .cmd }}'
      args: '{{ .args }}'
    cmds:
      - |
        docker compose \
          -p {{ .p | quote }} \
          -f {{ .f | quote }} \
          {{ .cmd | quote -}}
          {{- if .args }} {{ .args }}{{ end }}
  apply:
    vars:
      p: '{{ .p }}'
      f: '{{ .f }}'
    cmds:
      - task: _apply
        vars:
          p: '{{ .p }}'
          f: '{{ .f }}'
          cmd: up
          args: -d
  delete:
    vars:
      p: '{{ .p }}'
      f: '{{ .f }}'
    cmds:
      - task: _apply
        vars:
          p: '{{ .p }}'
          f: '{{ .f }}'
          cmd: down
  logs:
    vars:
      p: '{{ .p }}'
      f: '{{ .f }}'
    cmds:
      - task: _apply
        vars:
          p: '{{ .p }}'
          f: '{{ .f }}'
          cmd: logs
          args: -f
  top:
    vars:
      p: '{{ .p }}'
      f: '{{ .f }}'
    cmds:
      - task: _apply
        vars:
          p: '{{ .p }}'
          f: '{{ .f }}'
          cmd: top
  ls:
    vars:
      format: '{{ .format | default "table" }}'
    cmds:
      - docker compose ls --format {{ .format | quote }}
