---
ingresses:
  - enabled: true
    namespace: dragonfly-system
    name: dragonfly-manager
    tls: true
    host: dragonfly-manager
    path: /
    pathType: ImplementationSpecific
    service:
      name: dragonfly-manager
      port:
        number: 8080
  - enabled: true
    namespace: dragonfly-system
    name: dragonfly-scheduler
    tls: true
    host: dragonfly-scheduler
    path: /
    pathType: ImplementationSpecific
    service:
      name: dragonfly-scheduler
      port:
        number: 8002
