---
ingresses:
  - name: dragonfly-manager
    host: dragonfly-manager
    service:
      name: dragonfly-manager
      port:
        number: 8080
  - name: dragonfly-scheduler
    host: dragonfly-scheduler
    service:
      name: dragonfly-scheduler
      port:
        number: 8002
