---
ingresses:
  - name: dragonfly-manager
    host: dragonfly-manager
    service:
      name: dragonfly-manager
      port:
        name: http-rest
  - name: dragonfly-scheduler
    host: dragonfly-scheduler
    service:
      name: dragonfly-scheduler
      port:
        name: http-grpc
