---
txtOwnerId: kind

provider:
  name: cloudflare
domainFilters:
  - drewfro.org
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare
        key: apiKey

#provider:
#  name: godaddy
#domainFilters:
#  - myk8ssky.net
#env:
#  - name: EXTERNAL_DNS_GODADDY_API_KEY
#    valueFrom:
#      secretKeyRef:
#        name: external-dns-godaddy
#        key: apiKey
#  - name: EXTERNAL_DNS_GODADDY_API_SECRET
#    valueFrom:
#      secretKeyRef:
#        name: external-dns-godaddy
#        key: apiSecret
