---
redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__NAME
      valueFrom:
        secretKeyRef:
          name: gitea-pg-app
          key: dbname
    - name: GITEA__DATABASE__HOST
      valueFrom:
        secretKeyRef:
          name: gitea-pg-app
          key: host
    - name: GITEA__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: gitea-pg-app
          key: user
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea-pg-app
          key: password
service:
  http:
    annotations:
      tailscale.com/expose: 'true'
    port: 3000
    type: LoadBalancer
  ssh:
    annotations:
      tailscale.com/expose: 'true'
    port: 22
    type: LoadBalancer
