---
redis-cluster:
  enabled: false
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
service:
  http:
    annotations:
      tailscale.com/expose: 'true'
    port: 3000
    type: LoadBalancer
  ssh:
    annotations:
      tailscale.com/expose: 'true'
    port: 22
    type: LoadBalancer
