---
certmanager:
  install: false
global:
  hosts:
    domain: elephant-frog.ts.net
  ingress:
    class: tailscale
    provider: tailscale
    configureCertmanager: false
    annotations:
      'kubernetes.io/tls-acme': true
      'cert-manager.io/cluster-issuer': selfsigned-cluster-issuer
  pages:
    enabled: true
nginx-ingress:
  enabled: false
gitlab:
  webservice:
    ingress:
      tls:
        secretName: gitlab-gitlab-tls
  kas:
    ingress:
      tls:
        secretName: gitlab-kas-tls
registry:
  ingress:
    tls:
      secretName: gitlab-registry-tls
minio:
  ingres:
    tls:
      secretName: gitlab-minio-tls
