---
certmanager:
  install: false
global:
  hosts:
    domain: elephant-frog.ts.net
  ingress:
    class: tailscale
    provider: tailscale
    configureCertmanager: false
  initialRootPassword:
    secret: gitlab-root-password
    key: password
  pages:
    enabled: false
nginx-ingress:
  enabled: false
gitlab:
  kas:
    ingress:
      enabled: false
minio:
  ingress:
    enabled: false
