---
certmanager:
  install: false
global:
  ingress:
    enabled: false
  initialRootPassword:
    secret: gitlab-root-password
    key: password
  pages:
    enabled: false
nginx-ingress:
  enabled: false
gitlab:
  kas:
    ingress:
      enabled: false
  webservice:
    ingress:
      enabled: false
minio:
  ingress:
    enabled: false
registry:
  ingress:
    enabled: false
