---
caddy:
  enabled: false
postgres:
  primary:
    extendedConfiguration: |
      timezone = 'UTC'
api:
  deploymentEnvFrom:
    - secretRef:
        name: hatchet-config
    - secretRef:
        name: hatchet-shared-config
engine:
  deploymentEnvFrom:
    - secretRef:
        name: hatchet-config
    - secretRef:
        name: hatchet-shared-config
