---
gateways:
  - name: hatchet
    host: hatchet
    routes:
      - path: /api
        service:
          name: hatchet-stack-api
          port:
            number: 8080
      - path: /
        service:
          name: hatchet-stack-frontend
          port:
            number: 8080
