---
caddy:
  enabled: false
api:
  deploymentEnvFrom:
    - secretRef:
        name: hatchet-config
    - secretRef:
        name: hatchet-shared-config
engine:
  deploymentEnvFrom:
    - secretRef:
        name: hatchet-config
    - secretRef:
        name: hatchet-shared-config
