---
version: '3'
includes:
  repo: ingress-nginx-repo.yml
  helm:
    taskfile: helm.yml
    vars:
      namespace: ingress-nginx
      create_namespace: 'true'
      install: 'true'
      name: ingress-nginx
      chart_repo_name: ingress-nginx
      chart: ingress-nginx
      chart_ver: 4.10.0
tasks:
  default:
    deps:
      - upgrade
  upgrade:
    deps:
      - task: repo
    cmds:
      - task: helm:upgrade
  delete:
    cmds:
      - task: helm:delete
