---
version: '3'
includes:
  repo: ingress-nginx-repo.yml
  helm:
    taskfile: helm.yml
    vars:
      namespace: ingress-nginx
      create_namespace: true
      name: ingress-nginx
      chart_repo_name: ingress-nginx
      chart: ingress-nginx
      chart_ver: 4.7.0
tasks:
  default:
    deps:
      - install
  install:
    deps:
      - task: repo
    cmds:
      - task: helm:install
  delete:
    cmds:
      - task: helm:delete
