---
version: '3'
vars:
  spire: pet
  keycloak_operator: keycloak-operator
  keycloak: pet
  trivy_operator: pet
includes:
  spire:
    taskfile: '{{ .spire }}.yml'

  keycloak-operator:
    taskfile: '{{ .keycloak_operator }}.yml'

  keycloak:
    taskfile: '{{ .keycloak }}.yml'

  trivy-operator:
    taskfile: '{{ .trivy_operator }}.yml'
tasks:
  default:
    deps:
      - up
  up:
    cmds:
      - task: spire:upgrade
      - task: keycloak-operator:apply
      - task: keycloak:upgrade
      - task: trivy-operator:upgrade
  delete:
    cmds:
      - task: trivy-operator:delete
      - task: keycloak:delete
      - task: keycloak-operator:delete
      - task: spire:delete
  check:
    cmds:
      - task: spire:check
      - task: keycloak-operator:check
      - task: keycloak:check
      - task: trivy-operator:check
