---
version: '3'
includes:
  spire: spire.yml
#  spire: pet.yml

  keycloak-operator: keycloak-operator.yml
#  keycloak-operator: pet.yml

  keycloak: bitnami-keycloak.yml
#  keycloak: pet.yml

#  trivy-operator: trivy-operator.yml
  trivy-operator: pet.yml
tasks:
  default:
    deps:
      - up
  up:
    cmds:
      - task: spire:upgrade
      - task: keycloak-operator:apply
      - task: keycloak:upgrade
      - task: trivy-operator:upgrade
  delete:
    cmds:
      - task: trivy-operator:delete
      - task: keycloak:delete
      - task: keycloak-operator:delete
      - task: spire:delete
  check:
    cmds:
      - task: spire:check
      - task: keycloak-operator:check
      - task: keycloak:check
      - task: trivy-operator:check
