---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: keycloak
    spec:
      project: default
      source:
        chart: keycloak
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.3.1
        helm:
          releaseName: keycloak
      destination:
        server: '{{ url }}'
      syncPolicy:
        automated: {}
