---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bitnami-keycloak
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{ cluster }}-bitnami-keycloak'
    spec:
      project: default
      source:
        chart: keycloak
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.3.1
        helm:
          releaseName: bitnami-keycloak
      destination:
        server: '{{ url }}'
