---
# https://kiali.io/docs/configuration/kialis.kiali.io/
cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    external_services:
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090"
      grafana:
        enabled: true
        internal_url: "http://kube-prometheus-stack-grafana.kube-prometheus-stack.svc"
        dashboards:
          - name: "Istio Service Dashboard"
            variables:
              namespace: istio-system
          - name: "Istio Workload Dashboard"
            variables:
              namespace: istio-system
          - name: "Istio Mesh Dashboard"
          - name: "Istio Control Plane Dashboard"
          - name: "Istio Performance Dashboard"
          - name: "Istio Wasm Extension Dashboard"
      tracing:
        enabled: true
        provider: jaeger
        internal_url: "http://jaeger-collector.istio-system.svc:14268"
        use_grpc: false
