---
cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    external_services:
      tracing:
        enabled: false
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090"
