---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: komodorio
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: komodor-agent
    spec:
      project: default
      source:
        repoURL: registry-1.docker.io/komodorio
        chart: komodor-agent
        targetRevision: 2.3.0
        helm:
          releaseName: komodor-agent
      destination:
        server: '{{ url }}'
        namespace: komodorio
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
