---
version: '3'
includes:
  repo: prometheus-community-repo.yml
  helm:
    taskfile: helm.yml
    vars:
      namespace: kube-prometheus-stack
      create_namespace: 'true'
      install: 'true'
      name: kube-prometheus-stack
      chart_repo_name: prometheus-community
      chart: kube-prometheus-stack
      chart_ver: 56.7.0
tasks:
  default:
    deps:
      - upgrade
  install:
    deps:
      - task: repo
    cmds:
      - task: helm:upgrade
  delete:
    cmds:
      - task: helm:delete
