---
version: '3'
tasks:
  merge-all:
    vars:
      dotkube: '${HOME}/.kube'
      kubeconfigs_path: '{{ .dotkube }}/configs'
      all: '{{ .dotkube }}/all'
      kubeconfig: '{{ .dotkube }}/config'
    cmds:
      - |
        set -ex
        export KUBECONFIG="{{ .kubeconfig }}:$(find {{ .kubeconfigs_path }} -type f | tr '\n' ':')"
        kubectl config view --flatten > {{ .all | quote }}
        cp {{ .all | quote }} {{ .kubeconfig | quote }}
        chmod 600 {{ .kubeconfig | quote }}
