---
version: '3'
tasks:
  merge-all:
    vars:
      kubeconfigs_path: '{{ .USER_WORKING_DIR }}/.kubeconfigs'
      dotkube: '${HOME}/.kube'
      all: '{{ .dotkube }}/all'
      kubeconfig: '{{ .dotkube }}/config'
    cmds:
      - |
        set -ex
        export KUBECONFIG="{{ .kubeconfig }}:$(find {{ .kubeconfigs_path }} -type f | tr '\n' ':')"
        kubectl config view --flatten > {{ .all | quote }}
        mv {{ .all | quote }} {{ .kubeconfig | quote }}
