---
version: '3'
includes:
  repo: prometheus-community-repo.yml
  kk:
    taskfile: kubectl.yml
    vars:
      n: kube-prometheus-stack
      labels: istio.io/dataplane-mode=ambient
  helm:
    taskfile: helm.yml
    vars:
      namespace: kube-prometheus-stack
      name: kube-prometheus-stack
      chart_repo_name: prometheus-community
      chart: kube-prometheus-stack
      chart_ver: 82.13.1
  ingress:
    taskfile: tailscale-ingress.yml
    vars:
      namespace: kube-prometheus-stack
      name: tailscale-ingress
      helm_args: -f kube-prometheus-stack-tailscale-ingress-values.yml
tasks:
  default:
    deps:
      - upgrade
  test-secrets:
    vars:
      grafana_admin_password: '{{ .grafana_admin_password | default "${GRAFANA_ADMIN_PASSWORD}" }}'
    cmds:
      - test {{ .grafana_admin_password | quote }}
  upgrade:
    vars:
      grafana_admin_password: '{{ .grafana_admin_password | default "${GRAFANA_ADMIN_PASSWORD}" }}'
    deps:
      - task: repo
    cmds:
      - task: kk:ns-create
      - task: test-secrets
        vars:
          grafana_admin_password: '{{ .grafana_admin_password }}'
      - task: helm:upgrade
        vars:
          helm_args: >-
            -f kube-prometheus-stack-values.yml
            --set grafana.adminPassword={{ .grafana_admin_password | quote }}
      - task: ingress:upgrade
  delete:
    cmds:
      - task: ingress:delete
      - task: helm:delete
      - task: kk:ns-delete
  check:
    deps:
      - task: repo
    cmds:
      - task: helm:check
