---
version: '3'
includes:
  repo: prometheus-community-repo.yml
  kk:
    taskfile: kubectl.yml
    vars:
      n: kube-prometheus-stack
      labels: istio.io/dataplane-mode=ambient
  helm:
    taskfile: helm.yml
    vars:
      namespace: kube-prometheus-stack
      name: kube-prometheus-stack
      chart_repo_name: prometheus-community
      chart: kube-prometheus-stack
      chart_ver: 65.1.1
tasks:
  default:
    deps:
      - upgrade
  upgrade:
    deps:
      - task: repo
    cmds:
      - task: kk:ns-create
      - task: kk:ns-label
      - task: helm:upgrade
  delete:
    cmds:
      - task: helm:delete
      - task: kk:ns-delete
  check:
    deps:
      - task: repo
    cmds:
      - task: helm:check
