---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.200-172.18.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-ipaddresspool
