---
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:latest
    container_name: netbootxyz
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ./netbootxyz-dnsmasq.d:/etc/dnsmasq.d:ro
      - ./netbootxyz:/config:rw
      - ./netbootxyz-assets/asset-mirror:/assets/asset-mirror:ro
      - ./netbootxyz-harvester:/assets/harvester:ro
      - ./netbootxyz/menus/local:/assets/ipxe:ro
