---
version: '3'
includes:
  helm:
    taskfile: helm.yml
    vars:
      namespace: nginx-ingress
      upgrade: 'true'
      create_namespace: 'true'
      name: nginx-ingress
      chart: oci://ghcr.io/nginxinc/charts/nginx-ingress
      # https://docs.nginx.com/nginx-ingress-controller/installation/installing-nic/installation-with-helm/
      chart_ver: 1.3.1
tasks:
  default:
    deps:
      - install
  upgrade:
    cmds:
      - task: helm:upgrade
  delete:
    cmds:
      - task: helm:delete
