---
version: '3'
includes:
  helm:
    taskfile: helm.yml
    vars:
      namespace: nginx-ingress
      create_namespace: true
      name: nginx-ingress
      chart: oci://ghcr.io/nginxinc/charts/nginx-ingress
      chart_ver: 0.17.1
tasks:
  default:
    deps:
      - install
  install:
    cmds:
      - task: helm:install
  delete:
    cmds:
      - task: helm:delete
