---
services:
  registry:
    image: docker.io/mcronce/oci-registry:v0.3.13
    container_name: kind-registry
    command: filesystem
    environment:
      FILESYSTEM_ROOT: /registry_cache
      RUST_LOG: 'info,actix-web=debug'
    networks:
      - kind
    volumes:
      - registry_cache:/registry_cache:rw
networks:
  kind: {}
volumes:
  registry_cache: {}
