---
services:
  registry:
    image: docker.io/mcronce/oci-registry:v0.4.5
    container_name: kind-registry
    command: filesystem
    environment:
      - FILESYSTEM_ROOT=/registry_cache
      - RUST_LOG=info,actix-web=debug
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    restart: always
    volumes:
      - registry_cache:/registry_cache:rw
networks:
  default:
    name: kind
    external: true
volumes:
  registry_cache: {}
