---
opencost:
  prometheus:
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: kube-prometheus-stack
      port: 9090

service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9003"

serviceMonitor:
  enabled: true
  labels:
    app.kubernetes.io/name: opencost

ui:
  enabled: true
