---
- hosts: all
  vars:
    carvel_apps:
      - name: kapp
        version: 0.54.1
  roles:
    - andrewrothstein.k3d
    - andrewrothstein.kind
    - andrewrothstein.kubectl
    - andrewrothstein.istio
    - andrewrothstein.git
    - andrewrothstein.jq
    - andrewrothstein.task
    - andrewrothstein.pinniped
    - andrewrothstein.carvel
    - andrewrothstein.argocd
    - andrewrothstein.argo
    - andrewrothstein.kubefwd
    - andrewrothstein.kubeshark
    - andrewrothstein.kubernetes-helm
    - andrewrothstein.k9s
    - andrewrothstein.cluster_api
    - andrewrothstein.kubevirt
    - andrewrothstein.flux
    - andrewrothstein.cilium
    - andrewrothstein.minio
    - andrewrothstein.vault
    - andrewrothstein.velero
