---
collections:
  - ansible.posix
  - community.windows
roles:
  - andrewrothstein.k3d
  - andrewrothstein.kind
  - andrewrothstein.kubectl
  - andrewrothstein.istio
  - andrewrothstein.gh
  - andrewrothstein.git
  - andrewrothstein.jq
  - andrewrothstein.task
  - andrewrothstein.pinniped
  - andrewrothstein.carvel
  - andrewrothstein.argocd
  - andrewrothstein.argo
  - andrewrothstein.kubefwd
  - andrewrothstein.kubeshark
  - andrewrothstein.kubernetes-helm
  - andrewrothstein.helmfile
  - andrewrothstein.k9s
  - andrewrothstein.cluster_api
  - andrewrothstein.kubevirt
  - andrewrothstein.flux
  - andrewrothstein.cilium
  - andrewrothstein.minio
  - andrewrothstein.vault
  - andrewrothstein.velero
  - andrewrothstein.jq
  - andrewrothstein.terraform
  - andrewrothstein.terragrunt
  - andrewrothstein.packer
  - andrewrothstein.vault
  - andrewrothstein.consul
  - andrewrothstein.nomad
