---
collections:
  - ansible.posix
  - community.windows
  - community.hashi_vault
  - community.kubernetes
roles:
  - andrewrothstein.sudoers
  - andrewrothstein.docker_compose
  - andrewrothstein.k3sup
  - andrewrothstein.k3d
  - andrewrothstein.kind
  - andrewrothstein.kubectl
  - andrewrothstein.kubelogin
  - andrewrothstein.istio
  - andrewrothstein.gh
  - andrewrothstein.git
  - andrewrothstein.jq
  - andrewrothstein.task
  - andrewrothstein.pinniped
  - andrewrothstein.carvel
  - andrewrothstein.argocd
  - andrewrothstein.argo
  - andrewrothstein.kubefwd
  - andrewrothstein.kubeshark
  - andrewrothstein.kubernetes_helm
  - andrewrothstein.helmfile
  - andrewrothstein.gator
  - andrewrothstein.opa
  - andrewrothstein.k9s
  - andrewrothstein.cluster_api
  - andrewrothstein.vcluster
  - andrewrothstein.kubevirt
  - andrewrothstein.flux
  - andrewrothstein.cilium
  - andrewrothstein.minio
  - andrewrothstein.vault
  - andrewrothstein.velero
  - andrewrothstein.jq
  - andrewrothstein.terraform
  - andrewrothstein.terragrunt
  - andrewrothstein.packer
  - andrewrothstein.vault
  - andrewrothstein.consul
  - andrewrothstein.nomad
  - andrewrothstein.dolt
  - andrewrothstein.liquibase
  - andrewrothstein.go_dev
  - andrewrothstein.pack
  - andrewrothstein.kn
  - andrewrothstein.kubeseal
  - andrewrothstein.calicoctl
  - andrewrothstein.pki
  - andrewrothstein.operator_sdk
  - andrewrothstein.olm
  - andrewrothstein.trident
  - andrewrothstein.trivy
