---
version: '3'
includes:
  helm:
    taskfile: helm.yml
    vars:
      kubeconfig: '{{ .kubeconfig | default (env "KUBECONFIG") }}'
      kube_context: '{{ .kube_context | default (env "KUBE_CONTEXT") }}'
tasks:
  upgrade:
    vars:
      namespace: '{{ .namespace }}'
      name: '{{ .name }}'
      chart: '{{ .chart | default "chart-tailscale-ingress" }}'
      default_subdomain:
        sh: printf '%s' "${TAILSCALE_SUBDOMAIN:-$(hostname)}"
      subdomain: '{{ .subdomain | default .default_subdomain }}'
      helm_args: '{{ .helm_args }}'
    cmds:
      - task: helm:upgrade
        vars:
          namespace: '{{ .namespace }}'
          name: '{{ .name }}'
          chart: '{{ .chart }}'
          helm_args: '{{ .helm_args }} --set subdomain={{ .subdomain }}'
  delete:
    vars:
      namespace: '{{ .namespace }}'
      name: '{{ .name }}'
    cmds:
      - task: helm:delete
        vars:
          namespace: '{{ .namespace }}'
          name: '{{ .name }}'
