---
version: '3'
includes:
  k8s: k8s.yml
#  k8s: pet.yml

#  mesh: istio.yml
  mesh: pet.yml

  pre-mesh: pre-mesh.yml
#  pre-mesh: pet.yml

  post-mesh: post-mesh.yml
#  post-mesh: pet.yml
tasks:
  up:
    cmds:
      - task: k8s:up
      - task: pre-mesh:up
      - task: mesh:up
      - task: post-mesh:up
  delete:
    cmds:
#      - task: post-mesh:delete
#      - task: mesh:delete
#      - task: pre-mesh:delete
      - task: k8s:delete
  default:
    deps:
      - up
