---
version: '3'
dotenv:
  - .vault-secrets.yml
includes:
  k8s: k8s.yml
#  k8s: pet.yml

  mesh: istio.yml
#  mesh: pet.yml

  post-mesh-1: post-mesh-1.yml
#  post-mesh-1: pet.yml

  post-mesh-2: post-mesh-2.yml
#  post-mesh-2: pet.yml

  working: working.yml
#  working: pet.yml

tasks:
  up:
    cmds:
      - task: k8s:up
      - task: mesh:up
      - task: post-mesh-1:up
      - task: post-mesh-2:up
      - task: working:up
  delete:
    cmds:
#      - task: post-mesh-2:delete
#      - task: post-mesh-1:delete
#      - task: mesh:delete
      - task: k8s:delete
  destroy:
    cmds:
      - task: k8s:destroy
  default:
    deps:
      - up
