---
version: '3'
includes:
  k8s: kind+registry.yml
  # mesh: istio.yml
  pre-mesh: pre-mesh.yml
  post-mesh: post-mesh.yml
tasks:
  up:
    cmds:
      - task: k8s:up
      - task: pre-mesh:up
#      - task: mesh:up
#      - task: post-mesh:up
  delete:
    cmds:
#      - task: post-mesh:delete
#      - task: mesh:delete
      - task: pre-mesh:delete
      - task: k8s:delete
  default:
    deps:
      - up
