---
version: '3'
includes:
  ansible-playbook-local:
    taskfile: apps/ansible-playbook-local/Taskfile.yml
    dir: apps/ansible-playbook-local
  tf-dex-aad:
    taskfile: apps/tf-dex-aad/Taskfile.yml
    dir: apps/tf-dex-aad
  k8s: tasks/kind.yml
#  k8s: tasks/k3d.yml
  pinniped: tasks/pinniped.yml
  istio: tasks/istio.yml
  argocd: tasks/argocd.yml
  argo: tasks/argo.yml
  argo-events: tasks/argo-events.yml
  argo-rollouts: tasks/argo-rollouts.yml
  gitea: tasks/gitea.yml
  hashicorp: tasks/hashicorp.yml
  jetstack: tasks/jetstack.yml
  gatekeeper: tasks/gatekeeper.yml
  cluster_api: tasks/cluster_api.yml
  kubevirt: tasks/kubevirt.yml
  kubevirt-vms:
    dir: apps/kubevirt-vm
    taskfile: apps/kubevirt-vm/Taskfile.yml
tasks:
  pre-mesh-up:
    deps:
      - k8s:up
    cmds:
#      - task: gatekeeper:install
      - task: hashicorp:vault-install
#      - task: pinniped:deploy-concierge
#      - task: jetstack:install
  pre-mesh-delete:
    deps:
#      - jetstack:delete
#      - pinniped:delete-concierge
      - hashicorp:vault-delete
#      - gatekeeper:delete
  mesh-up:
    deps:
      - pre-mesh-up
    cmds:
      - task: istio:up
  up:
    deps:
      - mesh-up
    cmds:
      - task: argocd:apply
      - task: argo-events:apply
      - task: argo:apply
      - task: argo-rollouts:apply
#      - task: gitea:install
  mesh-delete:
    deps:
#      - gitea:delete
      - argo-rollouts:delete
      - argo:delete
      - argo-events:delete
      - argocd:delete
    cmds:
      - task: istio:delete
  delete:
    deps:
      - pre-mesh-delete
      - mesh-delete
    cmds:
      - task: k8s:delete
  default:
    deps:
      - up
