---
version: '3'
includes:
  ansible-playbook-local:
    dir: ansible-playbook-local
    taskfile: ansible-playbook-local.yml
  tf-dex-aad:
    dir: tf-dex-aad
    taskfile: tf-dex-aad.yml
  k8s: kind.yml
  k3d: k3d.yml
  kind: kind.yml
  istio: istio.yml
  pre-mesh: pre-mesh.yml
  post-mesh: post-mesh.yml
tasks:
  up:
    cmds:
      - task: k8s:up
      - task: pre-mesh:up
#      - task: istio:up
#      - task: post-mesh:up
  delete:
    cmds:
#      - task: post-mesh:delete
#      - task: istio:delete
      - task: pre-mesh:delete
      - task: k8s:delete
