---
server:
  replicaCount: 1
  config:
    namespaces:
      create: true
      namespace:
        - name: default
          retention: 3d
    persistence:
      defaultStore: default
      visibilityStore: visibility
      datastores:
        default:
          sql:
            # the databases are created by the cnpg cluster's initdb
            createDatabase: false
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal
            connectAddr: temporal-pg-chart-cnpg-instance-rw:5432
            connectProtocol: tcp
            user: temporal
            existingSecret: temporal-pg-user
            secretKey: password
        visibility:
          sql:
            createDatabase: false
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal_visibility
            connectAddr: temporal-pg-chart-cnpg-instance-rw:5432
            connectProtocol: tcp
            user: temporal
            existingSecret: temporal-pg-user
            secretKey: password

web:
  enabled: true

admintools:
  enabled: true
