---
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      accessMode: ReadWrite
      default: true
      config:
        region: us-east-1
        s3ForcePathStyle: true
        s3Url: http://minio.velero.svc.cluster.local
        publicUrl: http://minio.velero.svc.cluster.local
  volumeSnapshotLocation:
    - name: my-volume-snapshot-location
      provider: aws
      config:
        region: us-east-1
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.0
    volumeMounts:
      - mountPath: /target
        name: plugins
credentials:
  existingSecret: velero-minio-credentials
