---
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      accessMode: ReadWrite
      default: true
      config:
        region: us-east-1
        s3ForcePathStyle: true
        s3Url: http://minio-hl:9000
        publicUrl: http://minio-hl:9000
  volumeSnapshotLocation:
    - name: my-volume-snapshot-location
      provider: aws
      config:
        region: us-east-1
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.1
    volumeMounts:
      - mountPath: /target
        name: plugins
