[project]
name = "uv-ftw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andrew Rothstein", email = "andrew.rothstein@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
uv-ftw = "uv_ftw:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
