---
version: '3'
tasks:
  galaxy-deps:
    vars:
      requirements: '{{ .requirements | default "requirements.yml" }}'
    cmds:
      - |
        if [ -e {{ .requirements | quote }} ];
        then
          ansible-galaxy install -r {{ .requirements | quote }}
        fi
  playbook:
    vars:
      limit: '{{ .limit | default "" }}'
      i: '{{ .i | default "" }}'
      c: '{{ .c | default "" }}'
      playbook: '{{ .playbook | default "playbook.yml" }}'
    cmds:
      - |
        ansible-playbook \
          {{ if .i }}-i {{ .i | quote }}{{ end }} \
          {{ if .c }}-c {{ .c | quote }}{{ end }} \
          {{ if .limit }}--limit {{ .limit | quote }}{{ end }} \
          {{ .playbook | quote }}
