---
version: '3'
includes:
  argo-raw:
    taskfile: argo-raw.yml
    internal: true
    vars:
      n: argo-events
      v: 1.7.3
      p: events
tasks:
  default:
    deps:
      - apply
  apply:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
    cmds:
      - task: argo-raw:apply
  delete:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
    cmds:
      - task: argo-raw:delete
