---
version: '3'
vars:
  DEFAULT_ARGO_ROLLOUTS_NS: argo-rollouts
  DEFAULT_ARGO_ROLLOUTS_VER: 1.3.0
includes:
  argo-proj:
    taskfile: argo-proj.yml
    vars:
      ARGO_PROJ_NS: '{{ .ARGO_ROLLOUTS_NS | default .DEFAULT_ARGO_ROLLOUTS_NS }}'
      ARGO_PROJ_NAME: rollouts
      ARGO_PROJ_VER: '{{ .ARGO_ROLLOUTS_VER | default .DEFAULT_ARGO_ROLLOUTS_VER }}'
    internal: true
tasks:
  apply:
    cmds:
      - task: argo-proj:apply
  delete:
    cmds:
      - task: argo-proj:delete