---
version: '3'
includes:
  argo-raw:
    taskfile: argo-raw.yml
    internal: true
    vars:
      n: argo-rollouts
      p: rollouts
      v: 1.3.0
tasks:
  default:
    deps:
      - apply
  apply:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
    cmds:
      - task: argo-raw:apply
  delete:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
    cmds:
      - task: argo-raw:delete
