---
version: '3'
vars:
  DEFAULT_ARGO_CD_NS: argo-cd
  DEFAULT_ARGO_CD_VER: 2.5.4
includes:
  argo-proj:
    taskfile: argo-proj.yml
    vars:
      ARGO_PROJ_NS: '{{ .ARGO_CD_NS | default .DEFAULT_ARGO_CD_NS }}'
      ARGO_PROJ_NAME: cd
      ARGO_PROJ_VER: '{{ .ARGO_CD_VER | default .DEFAULT_ARGO_CD_VER }}'
    internal: true
tasks:
  apply:
    cmds:
      - task: argo-proj:apply
  delete:
    cmds:
      - task: argo-proj:delete