---
version: '3'
includes:
  kubectl:
    taskfile: kubectl.yml
    internal: true
vars:
  ARGO_ROLLOUTS_NS: '{{ .ARGO_ROLLOUTS_NS | default "argo-rollouts" }}'
  ARGO_ROLLOUTS_VER: '{{ .ARGO_ROLLOUTS_VER | default "1.3.0" }}'
tasks:
  apply:
    cmds:
      - task: kubectl:ns-create
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
      - task: kubectl:apply
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
          f: https://github.com/argoproj/argo-rollouts/releases/download/v{{ .ARGO_ROLLOUTS_VER }}/install.yaml
  delete:
    cmds:
      - task: kubectl:delete
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
          f: https://github.com/argoproj/argo-rollouts/releases/download/v{{ .ARGO_ROLLOUTS_VER }}/install.yaml
      - task: kubectl:ns-delete
        vars:
          n: '{{ .ARGO_ROLLOUTS_NS }}'
