---
version: '3'
includes:
  argo-release:
    taskfile: argo-release.yml
    internal: true
    vars:
      n: argo
      v: 3.4.4
      p: workflows
tasks:
  default:
    deps:
      - apply
  apply:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
    cmds:
      - task: argo-release:apply
  delete:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
    cmds:
      - task: argo-release:delete
