---
version: '3'
vars:
  MIRROR: '{{ .MIRROR | default "https://github.com/argoproj" }}'
includes:
  kubectl:
    taskfile: kubectl.yml
    internal: true
tasks:
  apply:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
      y: '{{ .y | default "install.yaml" }}'
    cmds:
      - task: kubectl:ns-create
        vars:
          n: '{{ .n }}'
      - task: kubectl:apply
        vars:
          n: '{{ .n }}'
          f: '{{ .MIRROR }}/argo-{{ .p }}/releases/download/v{{ .v }}/{{ .y }}'
  delete:
    vars:
      n: '{{ .n }}'
      p: '{{ .p }}'
      v: '{{ .v }}'
      y: '{{ .y | default "install.yaml" }}'
    cmds:
      - task: kubectl:delete
        vars:
          n: '{{ .n }}'
          f: '{{ .MIRROR }}/argo-{{ .p }}/releases/download/v{{ .v }}/{{ .y }}'
      - task: kubectl:ns-delete
        vars:
          n: '{{ .n }}'
