---
version: '3'
includes:
  python:
    taskfile: python.yml
tasks:
  default:
    vars:
      dcbver: '{{ .dcbver | default "dcb == 0.1.2" }}'
      dcb: '{{ .dcb | default "dcb" }}'
      upstreamregistry: '{{ .upstreamregistry | default "ghcr.io" }}'
      upstreamgroup: '{{ .upstreamgroup | default "andrewrothstein" }}'
      upstreamapp: '{{ .upstreamapp | default "docker-ansible" }}'
      targetregistry: '{{ .targetregistry | default .upstreamregsitry }}'
      alltags: '{{ .alltags | default "" }}'
    cmds:
      - task: python:pip-install
        vars:
          pkg: '{{ .dcbver }}'
      - |
        cd {{ .USER_WORKING_DIR }};
        {{ .dcb | quote }} \
          --upstreamregistry {{ .upstreamregistry | quote }} \
          --upstreamgroup {{ .upstreamgroup | quote }} \
          --upstreamapp {{ .upstreamapp | quote }} \
          --targetregistry {{ .targetregistry | quote }} \
          --snippet from.j2 ansible-test-role.j2 \
          --pullall \
          --writeall \
          --buildall \
          {{ if .alltags }}--alltags {{ .alltags | quote }}{{ end }}
