---
version: '3'
vars:
  DEFAULT_NAME: kind-registry
  DEFAULT_CONTAINER_IMAGE: registry:2
includes:
  docker-daemon:
    taskfile: docker-daemon.yml
    internal: true
tasks:
  apply:
    cmds:
      - task: docker-daemon:apply
        vars:
          NAME: '{{ .NAME | default .DEFAULT_NAME }}'
          RESTART: always
          HOST_PORT: 5000
          CONTAINER_PORT: 5000
          CONTAINER_IMAGE: '{{ .CONTAINER_IMAGE | default .DEFAULT_CONTAINER_IMAGE }}'
          E: REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
  delete:
    cmds:
      - task: docker-daemon:delete
        vars:
          NAME: '{{ .NAME | default .DEFAULT_NAME }}'
