---
version: '3'
includes:
  helm:
    taskfile: helm.yml
    internal: true
tasks:
  helm-repo-add:
    cmds:
      - task: helm:repo-add
        vars:
          CHART_REPO_NAME: '{{ .CHART_REPO_NAME | default "hashicorp" }}'
          CHART_REPO_URL: '{{ .CHART_REPO_URL | default "https://helm.releases.hashicorp.com" }}'
