---
version: '3'
vars:
  CLUSTER_NAME: bootstrap
  K3S_ARGS: --disable=traefik@server:0
tasks:
  up:
    cmds:
      - k3d cluster create bootstrap --k3s-arg "{{ .K3S_ARGS }}"
    status:
      - k3d cluster list "{{ .CLUSTER_NAME }}"
  delete:
    cmds:
      - k3d cluster delete "{{ .CLUSTER_NAME }}"
    preconditions:
      - k3d cluster list "{{ .CLUSTER_NAME }}"
