---
version: '3'
includes:
  kapp: ./kapp.yml
vars:
  PINNIPED_VER: '{{ .PINNIPED_VER | default "0.20.0" }}'
  PINNIPED_CONCIERGE_NAME: '{{ .PINNIPED_CONCIERGE_NAME | default "pinniped-concierge" }}'
tasks:
  deploy-concierge:
    cmds:
      - task: kapp:deploy
        vars:
          APP: '{{ .PINNIPED_CONCIERGE_NAME }}'
          FILE: https://get.pinniped.dev/v{{ .PINNIPED_VER }}/install-pinniped-concierge.yaml
  delete-concierge:
    cmds:
      - task: kapp:delete
        vars:
          APP: '{{ .PINNIPED_CONCIERGE_NAME }}'

