---
version: '3'
includes:
  helm:
    taskfile: helm.yml
    internal: true
  kubectl:
    taskfile: kubectl.yml
    internal: true
vars:
  QUESTDB_CHART_REPO_NAME: questdb
  QUESTDB_CHART_REPO_URL: https://helm.questdb.io
  QUESTDB_CHART: questdb
  QUESTDB_CHART_VER: 0.27.0
  QUESTDB_NS: '{{ .QUESTDB_NS | default "questdb" }}'
  QUESTDB_NAME: '{{ .QUESTDB_NAME | default "my-questdb" }}'
tasks:
  helm-repo-add:
    internal: true
    cmds:
      - task: helm:repo-add
        vars:
          CHART_REPO_NAME: '{{ .QUESTDB_CHART_REPO_NAME }}'
          CHART_REPO_URL: '{{ .QUESTDB_CHART_REPO_URL }}'
  default:
    deps:
      - install
  install:
    vars:
      NAMESPACE: '{{ .NAMESPACE | default .QUESTDB_NS }}'
      NAME: '{{ .NAME | default .QUESTDB_NAME }}'
    deps:
      - helm-repo-add
    cmds:
      - task: kubectl:ns-create
        vars:
          n: '{{ .NAMESPACE }}'
      - task: helm:install
        vars:
          NAMESPACE: '{{ .NAMESPACE }}'
          NAME: '{{ .NAME }}'
          CHART_REPO_NAME: '{{ .QUESTDB_CHART_REPO_NAME }}'
          CHART: '{{ .QUESTDB_CHART }}'
          CHART_VER: '{{ .QUESTDB_CHART_VER }}'
  delete:
    vars:
      NAMESPACE: '{{ .NAMESPACE | default .QUESTDB_NS }}'
      NAME: '{{ .NAME | default .QUESTDB_NAME }}'
    cmds:
      - task: helm:delete
        vars:
          NAMESPACE: '{{ .NAMESPACE }}'
          NAME: '{{ .NAME }}'
      - task: kubectl:ns-delete
        vars:
          n: '{{ .NAMESPACE }}'
