---
version: '3'
tasks:
  workspace-list:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      WORKSPACE_NAME: '{{ .WORKSPACE_NAME | default "terraform-workspace" }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} workspace list'
  workspace-select:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      WORKSPACE_NAME: '{{ .WORKSPACE_NAME | default "terraform-workspace" }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} workspace select {{ .WORKSPACE_NAME | quote }}'
    status:
      - '{{ .TERRAFORM_EXE }} workspace list | grep "* {{ .WORKSPACE_NAME }}"'
  workspace-new:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      WORKSPACE_NAME: '{{ .WORKSPACE_NAME | default "terraform-workspace" }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} workspace new {{ .WORKSPACE_NAME | quote }}'
    status:
      - '{{ .TERRAFORM_EXE }} workspace list | grep {{ .WORKSPACE_NAME | quote }}'
  workspace-delete:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      WORKSPACE_NAME: '{{ .WORKSPACE_NAME | default "terraform-workspace" }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} workspace delete {{ .WORKSPACE_NAME }}'
  init:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      CHDIR: '{{ .CHDIR | default "." }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} -chdir={{ .CHDIR }} init -input=false'
  validate:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      CHDIR: '{{ .CHDIR | default "." }}'
      VALIDATE_JSON_OUTPUT: '{{ .VALIDATE_JSON_OUTPUT | default "tf-validate.json" }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} -chdir={{ .CHDIR }} validate -json -no-color | tee {{ .VALIDATE_JSON_OUTPUT }}'
  plan:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      CHDIR: '{{ .CHDIR | default "." }}'
      TFPLAN: '{{ .TFPLAN | default "tfplan" }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} -chdir={{ .CHDIR }} plan -input=false -out={{ .TFPLAN }}'
  apply:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      CHDIR: '{{ .CHDIR | default "." }}'
      TFPLAN: '{{ .TFPLAN | default "tfplan" }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} -chdir={{ .CHDIR }} apply -input=false {{ .TFPLAN }}'
  destroy:
    vars:
      TERRAFORM_EXE: '{{ .TERRAFORM_EXE | default "terraform" }}'
      CHDIR: '{{ .CHDIR | default "." }}'
    cmds:
      - '{{ .TERRAFORM_EXE }} -chdir={{ .CHDIR }} apply -destroy -input=false'
