# templates/pvc.yml
{{- if .Values.persistence.downloads.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transmission.fullname" . }}-downloads
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessMode }}
  {{- if .Values.persistence.downloads.storageClass }}
  storageClassName: {{ .Values.persistence.downloads.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size }}
{{- end }}
{{- if .Values.persistence.watch.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transmission.fullname" . }}-watch
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.watch.accessMode }}
  {{- if .Values.persistence.watch.storageClass }}
  storageClassName: {{ .Values.persistence.watch.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.watch.size }}
{{- end }}
