# templates/secret.yml
{{- if not .Values.auth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}-auth
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
{{- end }}
