---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-doppler-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: argocd-secrets
    creationPolicy: Owner
  data:
    - secretKey: ARGOCD_ADMIN_PASSWORD
      remoteRef:
        key: ARGOCD_ADMIN_PASSWORD