---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: vault-system
  name: status
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      probe status of vault
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        env:
          - name: VAULT_ADDR
            value: http://vault:8200
        image: hashicorp/vault
        args:
          - status
