---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: vault-status-
  annotations:
    workflows.argoproj.io/description: |
      probe status of vault
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        env:
          - name: VAULT_ADDR
            value: http://vault:8200
        image: hashicorp/vault:1.16.1
        args:
          - status
