---
coder:
  emv:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: CODER_AUTO_IMPORT_TEMPLATES
      value: kubernetes
