# Proxy DHCP - works alongside existing DHCP server
port=0
dhcp-range=192.168.1.0,proxy
log-dhcp

# TFTP
enable-tftp
tftp-root=/config/menus

# PXE handoff
pxe-service=x86PC,"netboot.xyz",netboot.xyz.kpxe
pxe-service=x86-64_EFI,"netboot.xyz UEFI",netboot.xyz.efi
pxe-service=BC_EFI,"netboot.xyz UEFI PXE-BC",netboot.xyz.efi
