---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "chart-strimzi-kafka.fullname" $ }}
spec:
  kafka:
    version: {{ $.Values.kafka.version }}
    replicas: {{ $.Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ $.Values.offsets.topic.replication.factor }}
      transaction.state.log.replication.factor: {{ $.Values.transaction.state.log.replication.factor }}
      transaction.state.log.min.isr: {{ $.Values.transaction.state.log.min.isr }}
      default.replication.factor: {{ $.Values.default.replication.factor }}
      min.insync.replicas: {{ $.Values.min.insync.replicas }}
      inter.broker.protocol.version: {{ $.Values.inter.broker.protocol.version | quote }}
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ $.Values.kafka.pvcSize }}
        deleteClaim: {{ $.Values.kafka.deleteClaim }}
  zookeeper:
    replicas: {{ $.Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ $.Values.zookeeper.pvcSize }}
      deleteClaim: {{ $.Values.zookeeper.deleteClaim }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
