---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
{{- range $i := until (int $.Values.controlPlaneNodeCount) }}
  - role: control-plane
    {{- include "kind.node" $.Values | nindent 4 }}
{{- end }}
{{- range $j := until (int $.Values.workloadNodeCount) }}
  - role: worker
    {{- include "kind.node" $.Values | nindent 4 }}
{{- end }}
networking:
{{- with $.Values.ipFamily }}
  ipFamily: {{ . | quote }}
{{- end }}
{{- with $.Values.apiServerAddress }}
  apiServerAddress: {{ . | quote }}
{{- end }}
{{- with $.Values.apiServerPort }}
  apiServerPort: {{ . }}
{{- end }}
  disableDefaultCNI: {{ $.Values.disableDefaultCNI | default false }}
{{- with $.Values.podSubnet }}
  podSubnet: {{ . | quote }}
{{- end }}
{{- with $.Values.serviceSubnet }}
  serviceSubnet: {{ . | quote }}
{{- end }}
{{- with $.Values.kubeProxyMode }}
  kubeProxyMode: {{ . | quote }}
{{- end }}
{{- with $.Values.containerdConfigPatches }}
containerdConfigPatches:
{{- . | toYaml | nindent 2 }}
{{- end }}
