---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  # https://marketplace.upbound.io/providers/upbound/provider-aws/v0.47.1
  package: xpkg.upbound.io/upbound/provider-aws:v0.47.1
