---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure
spec:
  # https://marketplace.upbound.io/providers/upbound/provider-family-azure
  package: xpkg.upbound.io/upbound/provider-family-azure:v1.5.0
