---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azuread
spec:
  # https://marketplace.upbound.io/providers/upbound/provider-azuread/v0.9.0
  package: xpkg.upbound.io/upbound/provider-azuread:v0.9.0
