---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
spec:
  # https://marketplace.upbound.io/providers/upbound/provider-family-gcp
  package: xpkg.upbound.io/upbound/provider-family-gcp:v1.8.1
