---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-vault
spec:
  # https://marketplace.upbound.io/providers/upbound/provider-vault/v1.0.0
  package: xpkg.upbound.io/upbound/provider-vault:v1.0.0
