{{- $fullname := include "tailscale-ingress.fullname" . }}
{{- $labels := include "tailscale-ingress.labels" . }}
{{- $subdomain := .Values.subdomain }}
{{- range $g := .Values.gateways }}
{{- $host := include "tailscale-ingress.host" (dict "host" $g.host "subdomain" $subdomain) }}
{{- if ($g.enabled | default true) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-{{ $g.name }}-gw
  labels:
    {{- $labels | nindent 4 }}
  {{- with $g.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $g.ingressClassName | default "tailscale" }}
  {{- if ($g.tls | default true) }}
  tls:
    - hosts:
        - {{ $host | quote }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullname }}-{{ $g.name }}-istio
                port:
                  number: 80
{{- end }}
{{- end }}
