---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedora
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/40.20240825.3.0/x86_64/fedora-coreos-40.20240825.3.0-metal.x86_64.raw.xz
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
