---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedora
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: https://ftp-chi.osuosl.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
