---
nameOverride: ""
fullnameOverride: ""

kafka:
  version: 3.6.0
  pvcSize: 100Gi
  replicas: 3
  deleteClaim: true
zookeeper:
  pvcSize: 100Gi
  replicas: 3
  deleteClaim: true
offsets:
  topic:
    replication:
      factor: 3
transaction:
  state:
    log:
      min:
        isr: 2
      replication:
        factor: 3
default:
  replication:
    factor: 3
min:
  insync:
    replicas: 2
inter:
  broker:
    protocol:
      version: '3.6'
