---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    'istio.io/dataplane-mode': ambient
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    istio:
      local-gateways: |
        - name: knative-local-gateway
          namespace: knative-serving
          service: knative-local-gateway.istio-system.svc.cluster.local
