# templates/deployment.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "git-cache.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "git-cache.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "git-cache.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: varnish-nconfig
              mountPath: /etc/nginx
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
        - name: varnish
          image: "{{ .Values.varnish.image.repository }}:{{ .Values.varnish.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: VARNISH_HTTP_PORT
              value: "8080"
          volumeMounts:
            - name: varnish-vconfig
              mountPath: /etc/varnish
            - name: varnish-data
              mountPath: /var/lib/varnish
          resources:
            {{- toYaml .Values.varnish.resources | nindent 12 }}
      volumes:
        - name: varnish-vconfig
          configMap:
            name: {{ include "git-cache.fullname" . }}-vconfig
        - name: varnish-nconfig
          configMap:
            name: {{ include "git-cache.fullname" . }}-nconfig
        - name: varnish-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "git-cache.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
