# values.yaml
varnish:
  image:
    repository: varnish
    tag: 7
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 4Gi
      cpu: 2
    requests:
      memory: 2Gi
      cpu: 500m
nginx:
  image:
    repository: nginx
    tag: 1
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 512Mi
      cpu: 500m

replicaCount: 1

persistence:
  enabled: true
  size: 20Gi

service:
  type: ClusterIP
  port: 80
