---
version: '3'
includes:
  pipenv: ../pipenv.yml
tasks:
  install:
    cmds:
      - task: pipenv:install
        vars:
          install_args: -r requirements.txt
  db-migrate:
    cmds:
      - task: pipenv:run
        vars:
          run_args: airflow db migrate
  webserver:
    cmds:
      - task: pipenv:run
        vars:
          run_args: airflow webserver -p 80
