---
- name: Install metallb
  hosts:
    - localhost
  tasks:
    - name: Add metallb helm chart repository
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
    - name: Install metallb/metallb
      kubernetes.core.helm:
        chart_ref: metallb/metallb
        chart_version: 0.13.12
        create_namespace: "true"
        release_name: metallb
        release_namespace: metallb-system
        context: gateway
        state: present
    - name: Define IPAddressPool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: metallb-ipaddresspool
            namespace: metallb-system
          spec:
            addresses:
              - 10.88.0.1-10.88.0.254
    - name: Define L2Advertisement
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: metallb-l2advertisement
            namespace: metallb-system
          spec:
            ipAddressPools:
              - metallb-ipaddresspool
