---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: keycloak
    spec:
      project: default
      source:
        repoURL: registry-1.docker.io/bitnamicharts
        chart: keycloak
        targetRevision: 18.7.1
        helm:
          releaseName: keycloak
      destination:
        server: '{{ url }}'
        namespace: default
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
