---
version: '3'
includes:
  pipenv:
    internal: true
    taskfile: ../pipenv.yml
    vars:
      r: requirements.txt
tasks:
  default:
    cmds:
      - task: pipenv:install
      - task: pipenv:run-python
