---
version: '3'
includes:
  pipenv:
    internal: true
    taskfile: ../pipenv.yml
tasks:
  default:
    cmds:
      - task: pipenv:install
        vars:
          install_args: -r requirements.txt
      - task: pipenv:run
        vars:
          run_args: python main.py
