---
'on':
  push:
    branches:
      - develop
      - 'feature/**'
  schedule:
    - cron: '0 0 * * *'
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      dist: ${{ steps.read-matrix.outputs.dist }}
    steps:
      - uses: actions/checkout@v4
      - name: read platform-matrix-v1.json
        id: read-matrix
        run: echo "dist=$(jq -cr '@json' < platform-matrix-v1.json)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - uses: docker/bake-action@v4
        env:
          UPSTREAM_IMAGE_TAG: "0.0.0-${{ matrix.dist.OS }}.${{ matrix.dist.OS_VER }}"
          TARGET_IMAGE_TAG: "0.0.0-${{ matrix.dist.OS }}.${{ matrix.dist.OS_VER }}"
        with:
          pull: true
          push: true
          files: docker-bake.hcl
          targets: only
    strategy:
      fail-fast: false
      matrix:
        dist: ${{ fromJSON(needs.prepare-matrix.outputs.dist) }}
