---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-containerservice
spec:
  # https://marketplace.upbound.io/providers/upbound/provider-azure-containerservice/v2.3.0
  package: xpkg.upbound.io/upbound/provider-azure-containerservice:v2.3.0
